package com.Grandeur.GranduerBackend.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Client {
    @Id// primary key annotation //
    // Automatically generated and incremented //
    @GeneratedValue(strategy = GenerationType.AUTO)
    // userId that's used to uniquely identify for every user  (automatically  generated by JPA) //
    private Long id;

    private String email; // userEmail //
    private String password; // userPassword //

    // Parameterized constructor //
    public Client(String email, String password){
        this.email = email;
        this.password = password;
    }

    // default Constructor //
    public Client() {}

    // GETTERS AND SETTERS for all the variables //
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
